### ISSUE TITLE
建议: 明确第三方依赖的引入时机

### ISSUE THREAD

**Issue by jwenjian** [nackily/imglib#1]
看了 Readme 之后, 对于什么时候需要自己引入第三方项目的依赖不太明白.

> 尽管 imglib 在某些图像处理能力上借助了这些优秀的第三方依赖，但 imglib 在打包后并未包含相关的依赖项。 如果有需要，您应该独立添加相应的依赖到项目中。

如果可以列出, 用户要使用哪些功能, 你应该引入哪个依赖, 会更清晰.

另外, 打包的时候是不是也可以把依赖项带上, 如果用户想自己引入依赖项, 可以通过 maven exclusions 来实现, 这样对于大多数用户来说就不必担心依赖的问题了.

**Comment by nackily** [comment]
感谢您的建议，我已添加了相关的来描述在何时需要引入第三方依赖并且提供了相应的样例，

**Comment by nackily** [comment]
与此相关的内容请参考[链接](https://github.com/nackily/imglib/blob/master/docs/Dependencies.md)。另外，将所有依赖项统一打包的建议我并不打算考虑，我无法保证其他第三方依赖是否永远开源，是否会更改开源协议，这样能让该项目更加纯粹。再次感谢您的建议！
