### ISSUE TITLE
编译报错

### ISSUE THREAD

**Issue by undefinedErr** [nackily/imglib#6]
使用最新版本依赖，
<dependency>
    <groupId>io.github.nackily</groupId>
    <artifactId>imglib-all</artifactId>
    <version>0.2.10</version>
</dependency>
 ImagePipes.ofEmptySource()
                    .register(new HashImageGenerator.Builder("Imglib")      // hash 图像生成器
                            .gridVerticalNum(8)                             // 水平方向的点阵数量
                            .bgColor(ColorUtils.of(240, 240, 240))          // 背景色
                            .fgColor(ColorUtils.of(50, 150, 50))
                            .build())
                    .toThumbnails()                                         // 转换为 Thumbnails
                    .addFilter(new HighQualityExpandHandler.Builder()       // 图像无损放大处理器
                            .finalWidth(150)                                // 图像的宽度
                            .keepAspectRatio(true)                          // 保持长宽比例
                            .build())
                    .addFilter(new BorderHandler.Builder()                  // 边框处理器
                            .fillColor(ColorUtils.of(240, 240, 240))        // 边框填充色
                            .vMargins(15)                                   // 垂直方向的边距
                            .hMargins(15)                                   // 水平方向的边距
                            .alpha(1.0f)                                    // 边框透明度
                            .build())
                    .scale(1.0)
                    .toFile(".../avatar.png");这段代码，编译失败，没有.addFilter方法

**Comment by nackily** [comment]
还需要Thumbnails的依赖哦，README中有提及到
